apiVersion: v1
kind: Service
metadata:
  name: c5-api
  namespace: c5
  labels:
    app.kubernetes.io/name: c5
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: c5-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: c5
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
